testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51OueI2RuxBVcx5SULvnGlVEv4J3hxwjRy3QMXCocSH6gwd8ofu9ncHVhkd8J1THD8WLSwZKJedMih0HfrxYsGuvL00GEyfvrfx" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_14k8zY2XX6CT6c0eUU" #only needed if using Stripe
client_id = "673628246785-52kehol0ro82bm7ftk7stefo223vulgv.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee
stripe_customer_portal_link = ""